on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Gradle
        uses: gradle/actions/action@v4
        with:
          gradle-version: "8.10"
      - name: Build project
        run: gradle build 
